/* Merch management. */
import '../auth.js';
import { createCollectionUi, moveFormToModal, pageItems } from './crud-ui.js';
import { addImageUploadFields, removeImage, resolveImageChange } from './media.js';

(() => {
  const root = document.querySelector('[data-admin-module="merch"]');
  if (!root) return;
  root.innerHTML = `<div class="merch-management"><div class="merch-management__intro"><p class="eyebrow">catalogo</p><h2>Gestione <em>merch.</em></h2><p>Crea e aggiorna i prodotti disponibili sul sito.</p></div><p class="merch-management__feedback" data-merch-feedback role="status" aria-live="polite"></p><form class="merch-management__form" data-merch-form><div class="merch-management__fields"><label>Nome prodotto<input name="name" minlength="2" maxlength="160" required /></label><label>Prezzo (€)<input name="price" type="number" min="0" step="0.01" required /></label><label class="merch-management__wide">Descrizione<textarea name="description" rows="4" maxlength="4000"></textarea></label><label class="merch-management__wide">URL immagine<input name="image_url" type="url" placeholder="https://…" /></label><label class="merch-management__toggle"><input name="available" type="checkbox" checked /> Disponibile</label><label class="merch-management__toggle"><input name="published" type="checkbox" /> Pubblicato sul sito</label></div><div class="merch-management__form-actions"><button class="button button-dark" type="submit"><span data-merch-submit-label>Aggiungi prodotto</span> <span>→</span></button><button class="link-button" type="button" data-merch-cancel>Annulla</button></div></form><div class="merch-management__list-wrap"><h3>Prodotti <em>catalogo.</em></h3><ul class="merch-management__list" data-merch-list aria-live="polite"></ul></div></div>`;
  const form = root.querySelector('[data-merch-form]');
  addImageUploadFields(form, { urlField: 'image_url' });
  const list = root.querySelector('[data-merch-list]');
  const feedback = root.querySelector('[data-merch-feedback]');
  const submit = form.querySelector('[type="submit"]');
  const cancel = form.querySelector('[data-merch-cancel]');
  const modal = moveFormToModal({ form, id: 'merch-edit-modal', title: 'Inserisci nuovo prodotto' });
  const collection = createCollectionUi({ root: root.querySelector('.merch-management__list-wrap'), list, addLabel: 'Inserisci nuovo prodotto', searchPlaceholder: 'Nome, descrizione o stato…' });
  let products = []; let editingId = null; let page = 1;
  const client = () => window.CapraiaAuth?.supabase;
  const say = (text = '', state = 'info') => { feedback.textContent = text; feedback.dataset.state = state; };
  const price = (value) => new Intl.NumberFormat('it-IT', { style: 'currency', currency: 'EUR' }).format(Number(value));
  const reset = () => { editingId = null; form.reset(); form.elements.available.checked = true; form.elements.published.checked = false; submit.querySelector('[data-merch-submit-label]').textContent = 'Aggiungi prodotto'; };
  const render = () => {
    const view = pageItems(products, collection.search.value, page, (product, query) => [product.name, product.description, product.published ? 'pubblicato' : 'bozza', product.available ? 'disponibile' : 'non disponibile'].join(' ').toLocaleLowerCase('it').includes(query));
    page = view.page; list.replaceChildren();
    if (!view.items.length) { const empty = document.createElement('li'); empty.textContent = 'Nessun prodotto trovato.'; list.append(empty); }
    view.items.forEach((product) => {
      const item = document.createElement('li'); item.className = 'merch-management__item'; item.dataset.merchId = product.id;
      if (product.image_url) { const image = document.createElement('img'); image.className = 'merch-management__image'; image.src = product.image_url; image.alt = ''; image.loading = 'lazy'; image.addEventListener('error', () => image.remove()); item.append(image); }
      const details = document.createElement('div'); details.className = 'merch-management__details'; const name = document.createElement('strong'); name.textContent = product.name; const amount = document.createElement('span'); amount.className = 'merch-management__price'; amount.textContent = price(product.price); const meta = document.createElement('small'); meta.textContent = `${product.published ? 'Pubblicato' : 'Bozza'} · ${product.available ? 'Disponibile' : 'Non disponibile'}`; details.append(name, amount, meta); if (product.description) { const text = document.createElement('p'); text.textContent = product.description; details.append(text); }
      const actions = document.createElement('div'); actions.className = 'merch-management__actions'; [['Modifica', 'edit'], ['Rimuovi', 'delete']].forEach(([label, action]) => { const button = document.createElement('button'); button.type = 'button'; button.textContent = label; button.dataset.merchAction = action; button.className = action === 'delete' ? 'merch-management__remove' : 'merch-management__edit'; actions.append(button); }); item.append(details, actions); list.append(item);
    });
    collection.renderPagination({ page, totalItems: view.filtered.length, onPageChange(next) { page = next; render(); } });
  };
  const load = async () => { const { data, error } = await client().from('merch_products').select('id, name, price, description, image_url, image_path, available, published, created_at').order('created_at', { ascending: false }); if (error) throw error; products = data || []; render(); };
  const fill = (product) => { editingId = product.id; form.elements.name.value = product.name; form.elements.price.value = Number(product.price).toFixed(2); form.elements.description.value = product.description || ''; form.elements.image_url.value = product.image_url || ''; form.elements.image_path.value = product.image_path || ''; form.elements.available.checked = product.available; form.elements.published.checked = product.published; submit.querySelector('[data-merch-submit-label]').textContent = 'Salva modifiche'; modal.open(`Modifica prodotto: ${product.name}`); };
  const payload = () => { const imageUrl = form.elements.image_url.value.trim(); if (imageUrl) { const parsed = new URL(imageUrl); if (!['http:', 'https:'].includes(parsed.protocol)) throw new Error('L’URL immagine deve usare HTTP o HTTPS.'); } const amount = Number(form.elements.price.value); if (!Number.isFinite(amount) || amount < 0) throw new Error('Inserisci un prezzo valido.'); return { name: form.elements.name.value.trim(), price: Math.round((amount + Number.EPSILON) * 100) / 100, description: form.elements.description.value.trim() || null, image_url: imageUrl || null, image_path: form.elements.image_path.value || null, available: form.elements.available.checked, published: form.elements.published.checked }; };
  const busy = async (operation) => { submit.disabled = true; root.setAttribute('aria-busy', 'true'); try { return await operation(); } finally { submit.disabled = false; root.removeAttribute('aria-busy'); } };
  collection.add.addEventListener('click', () => { reset(); modal.open('Inserisci nuovo prodotto'); });
  collection.search.addEventListener('input', () => { page = 1; render(); });
  cancel.addEventListener('click', () => { reset(); modal.close(); });
  form.addEventListener('submit', (event) => { event.preventDefault(); busy(async () => { const values = payload(); const image = await resolveImageChange({ form, folder: 'merch', urlField: 'image_url' }); values.image_url = image.url; values.image_path = image.path; const { error } = editingId ? await client().from('merch_products').update(values).eq('id', editingId) : await client().from('merch_products').insert(values); if (error) throw error; if (image.removePath && image.removePath !== image.path) await removeImage(image.removePath).catch(() => {}); const wasEditing = Boolean(editingId); reset(); modal.close(); await load(); say(wasEditing ? 'Prodotto aggiornato.' : 'Prodotto aggiunto al catalogo.', 'success'); }).catch((error) => say(error.message || 'Non è stato possibile salvare il prodotto.', 'error')); });
  list.addEventListener('click', (event) => { const button = event.target.closest('[data-merch-action]'); const product = products.find((item) => item.id === button?.closest('[data-merch-id]')?.dataset.merchId); if (!button || !product) return; if (button.dataset.merchAction === 'edit') return fill(product); if (!window.confirm(`Rimuovere definitivamente “${product.name}” dal catalogo?`)) return; busy(async () => { const { error } = await client().from('merch_products').delete().eq('id', product.id); if (error) throw error; await removeImage(product.image_path).catch(() => {}); await load(); say('Prodotto rimosso.', 'success'); }).catch((error) => say(error.message || 'Non è stato possibile rimuovere il prodotto.', 'error')); });
  (async () => { try { const access = await window.CapraiaAuth.requireOperator(); if (!access?.isOperator) throw new Error('Accesso negato.'); reset(); await load(); } catch { root.hidden = true; } })();
})();
